# Generated by Django 3.1 on 2020-08-07 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitnum',
            name='ttt_datime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 12, 44, 36, 225136), verbose_name='date published'),
        ),
    ]
